# Generated by Django 2.1.3 on 2018-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donador',
            name='categoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
